name: Codex Implementation
description: Codex 自動実装フロー向け Issue
title: "[codex] <type>: <対象> を <期待結果> にする"
labels:
  - codex:implement
  - type:feature
  - size:M
body:
  - type: markdown
    attributes:
      value: |
        この Issue は `codex:implement` ラベルをトリガーに自動実装されます。
        曖昧な記述は Spec QA でブロックされます。
  - type: textarea
    id: background
    attributes:
      label: 背景/目的
      description: 何を解決したいか、なぜ必要かを明確に記載してください。
      placeholder: |
        例:
        - 設定画面でテーマ初期化ができず、色設定が壊れた時に復旧できない
        - 1クリックで初期テーマに戻せるようにしたい
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受入条件
      description: 検証可能な条件を箇条書きで記載してください。
      placeholder: |
        - [ ] 設定画面に「テーマを初期化」ボタンが表示される
        - [ ] クリックで背景色/文字色/選択色が既定値に戻る
        - [ ] 再起動後も既定値が保持される
    validations:
      required: true
  - type: textarea
    id: out_of_scope
    attributes:
      label: 非対象
      description: 今回やらないことを明記してください。
      placeholder: |
        - 新規テーマプリセットの追加は行わない
        - フォント設定の仕様変更は行わない
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 補足（任意）
      description: 関連ログ、スクリーンショット、関連Issue/PRなど。
      placeholder: |
        - 関連: #123
        - スクリーンショット:
  - type: checkboxes
    id: checklist
    attributes:
      label: 起票チェック
      options:
        - label: 曖昧語（いい感じに/適切に 等）のみで受入条件を書いていない
          required: true
        - label: 非対象を明示し、受入条件と矛盾していない
          required: true
